### ISSUE TITLE
Buttons don't appear everywhere

### ISSUE THREAD

**Issue by deadcombo** [Skullbite/collapsible-ui#1]
Hello,

The toggle buttons only appear on the powercord server in some channels. On other servers I only see the hide members button.

Thank you this is very cool.

**Comment by Skullbite** [comment]
[This commit](https://github.com/Skullbite/collapsible-ui/commit/56a9e01910640aaf543615cd963b6a31552ce73d) allows it to show in DMs and Group DMs. As for things like the friends menu, I can't seem to find a place to inject there.

**Comment by deadcombo** [comment]
Yeah but the buttons aren't there for me in every server. I've only found 2 servers where the buttons display correctly.

Do your buttons display in all of your servers? Maybe it's a conflict with another plugin of mine.

**Comment by Skullbite** [comment]
Yes, all the buttons display properly, in any proper channel. Are there are any errors in the console when you're in said servers/channels?

**Comment by deadcombo** [comment]
No.

![image](https://user-images.githubusercontent.com/37187650/147827178-3eba7507-0528-4bb8-985b-41cd06f46501.png)

There's a few 404's but nothing to do with collapsible I think. Let me know how I can send you more info.
I have more addons using that space, maybe it's a conflict?

In #plugin-links:
![image](https://user-images.githubusercontent.com/37187650/147827247-04fc1233-4e76-4b1c-a877-1789e223ee47.png)

In #plugin-support:
![image](https://user-images.githubusercontent.com/37187650/147827278-da854dc1-d3b8-4787-b6e6-4882291a3c2e.png)

**Comment by Skullbite** [comment]
My best guess is you have too many buttons/components injected into the header bar. Not all of them are gonna show if there are too many.

**Comment by deadcombo** [comment]
Probably. Disabling the Link Preview Utility icon makes it work, it may be a direct conflict.

https://github.com/A-Trash-Coder/Link-Preview-Utility

Thanks Skullbite

**Comment by Skullbite** [comment]
mhm
